[package]
name = "nbodyrs"
version = "0.1.0"
authors = ["fish <mikail.khan45@gmail.com>"]
edition = "2018"

[dependencies]
quicksilver = "0.3.8"
nalgebra = "0.17.2"
rand = "0.6.5"
mint = "0.5.1"
rayon = "1.0.3"
microprofile = "0.0.2"
serde_json = "1.0"
